language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests

addons:
  sonarcloud:
    organization: "klaimbotay-github"
    token:
      secure: $SONAR_TOKEN

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
